# Generated by Django 4.0.4 on 2022-05-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Food Categories',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DishesTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pub.category')),
            ],
            options={
                'verbose_name_plural': 'Types Of Dishes',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1000)),
                ('prices', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Pub.prices')),
                ('type_of_food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Pub.dishestypes')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
    ]
